services:
  db:
    image: postgres:13                 
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_data:/var/lib/postgresql/data   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web                   
      dockerfile: Dockerfile
    container_name: nginx_web
    restart: always
    ports:
      - "8888:80"                      
    depends_on:
      db:
        condition: service_healthy     
